### ISSUE TITLE
Set journalctl retention policy to reasonable values

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/terraform_deployment#10]
System logs are growing quickly on worker nodes. We should consider applying some limits for log retention, e.g.:

```
journalctl --vacuum-size=500M
journalctl --vacuum-time=2d
```

**Comment by craig-willis** [comment]
It looks like we could also use journald.conf:

https://www.freedesktop.org/software/systemd/man/journald.conf.html

SystemMaxUse, SystemMaxFiles or MaxFileSec may work.
