### ISSUE TITLE
Mongo replication causing possible race condition

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/terraform_deployment#33]
When registering a dataset under certain circumstances, there is a 500 error during registration because a file is created in an item that doesn't exist since we are writing to primary and reading from secondary, which may not have the data.

Two solutions:
* Identify Mongo performance problem and resolve
* Deploy with single Mongo for now until we can resolve

**Comment by Xarthisius** [comment]
I believe that's fixed by https://github.com/whole-tale/girder/commit/c360d42f3dd23522f2693395a06031b847086a01
