### ISSUE TITLE
Increase VMs' resources

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/terraform_deployment#9]
It's not a pressing issue, but I'd like to increase the size of VMs from m1.small to at least m1.medium (maybe m1.large if it fits the allocation). For both dev and prod. Maybe next time when everything blows up... ;)

**Comment by craig-willis** [comment]
It looks like production was already deployed with 7 m1.medium (6 vcpu + 16G RAM) instances.  The  current TACC allocation has a quota of 132 vcpus + 360GB RAM.  We could use  m1.large (10 vcpu + 30GB RAM).  

I think it might make sense to leave m1.medium in the variables.tf?  Or we could parameterize based on environment.
